version: 2
updates:

  - package-ecosystem: 'github-actions'
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: npm
    directories:
      - /
      - amazongpt/
      - autoclear-chatgpt-history/
      - brave-omnibox/
      - bravegpt/
      - chatgpt-auto-continue/
      - chatgpt-auto-refresh/
      - chatgpt-auto-talk/
      - chatgpt-infinity/
      - chatgpt-omnibox/
      - chatgpt-widescreen/
      - deepseek-omnibox/
      - duckduckgpt/
      - googlegpt/
      - perplexity-omnibox/
      - phind-omnibox/
      - you.com-omnibox/
    schedule:
      interval: daily
    groups:
      dev-dependencies:
        dependency-type: development
