#!/bin/bash

RED="\033[1;31m" ; NC="\033[0m"
PROJECT_ROOT=$( # absolute path to echo on missing dependencies
    cd "$(dirname "$0")/.." && # nav to root
    [ "$OSTYPE" == "msys" ] && pwd -W || pwd # get absolute path
)

# Run ESLint for JavaScript + JSON + Markdown + YAML
if npm ls -g eslint &> /dev/null || npm ls eslint &> /dev/null ; then
    echo "Running ESLint..."
    npm run lint
else
    echo -e "\n${RED}Warning: ESLint not installed${NC}"
    echo -e "To add missing JS dependencies, run 'npm install' from"
    echo -e "$PROJECT_ROOT\n"
fi

# Run Ruff for Python
echo "Running Ruff..."
if command -v ruff &> /dev/null ; then
    ruff check .
else
    echo -e "\n${RED}Warning: Ruff not installed${NC}"
    echo -e "To add missing Python dependencies, run 'pip install -r requirements-dev.txt' from"
    echo -e "$PROJECT_ROOT\n"
fi
